config:
  port: 8080
  tls: false
  auth: true
  read_timeout: "15s"
  write_timeout: "15s"
  idle_timeout: "60s"

auth:
  - group: admins
    type: jwt
    jwt_secret: "supersecret"
    verify: 'have("admin") || have("superadmin")'

  - group: devops
    type: jwt
    jwt_secret: "devopssecret"
    verify: 'is("group","devops")'

  - group: basicusers
    type: basic
    users:
      - username: "alice"
        password_hash: "$2a$10$PvnUXAOm.dNZ8CLZFG925e8xl1EiQ.3HhD5TlTki8N5/kNCKAVVJC" # bcrypt hashed password

apis:
  - name: sales_api
    protocol: http
    permissions:
      - devops
    public: false
    routes:
      - path: /v1/sales
        upstreams:
          - host: localhost
            port: 8880
            tls: true
            tls_insecure: true
    cors:
      allowed_origins: ["*"]
      allowed_methods: ["GET", "POST", "OPTIONS"]
      allowed_headers: ["Authorization", "Content-Type"]
    rate_limit: 5
    load_balancing: round_robin
    headers:
      X-Custom-Header: "myproxy"
    cookies:
      mycookie: "value"
    max_retries: 2
    retry_delay_ms: 200
    fallback_response:
      status: 503
      body: '{"error": "service unavailable"}'

  - name: users_api
    protocol: http
    permissions:
      - admins
      - basicusers
    routes:
      - path: /v1/users
        upstreams:
          - host: localhost
            port: 8866
          - host: localhost
            port: 8844
    cors:
      allowed_origins: ["*"]
      allowed_methods: ["GET", "POST", "OPTIONS"]
      allowed_headers: ["Authorization", "Content-Type"]
    load_balancing: round_robin
    rate_limit: 5
    max_retries: 3
    retry_delay_ms: 100
    fallback_response:
      status: 503
      body: '{"error": "service unavailable"}'